services:
  - type: web
    name: flask-prediksi
    env: python
    buildCommand: ""
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DB_HOST
        value: sql12.freesqldatabase.com
      - key: DB_USER
        value: sql12787502
      - key: DB_PASSWORD
        value: AemMsVathz
      - key: DB_NAME
        value: sql12787502
